name: to_do_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  flutter_slidable: ^3.1.1
  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf

flutter_icons:
  image_path: "assets/TickIt Logo.jpeg"
  android: true
  ios: true
